pipeline {
    agent {
        docker {
            image 'gcc'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'make -C Triangle'
                sh 'make -C NextDate'
                sh 'make -C CommissionProblem'
            }
        }
        stage('Test') {
            steps {
                sh 'make -C Triangle test'
                sh 'make -C NextDate test'
                sh 'make -C CommissionProblem test'
            }
        }
    }
}