#include <limits.h>
#include "commission.h"
#include "gtest/gtest.h"
namespace {
	TEST(BoundaryValue, RobustWorstCase){
        EXPECT_EQ("Invalid items' amount", calcCommission(0, 0, 0));
        EXPECT_EQ("Invalid items' amount", calcCommission(0, 0, 1));
        EXPECT_EQ("Invalid items' amount", calcCommission(0, 0, 2));
        EXPECT_EQ("Invalid items' amount", calcCommission(0, 0, 45));
        EXPECT_EQ("Invalid items' amount", calcCommission(0, 0, 89));
        EXPECT_EQ("Invalid items' amount", calcCommission(0, 0, 90));
        EXPECT_EQ("Invalid items' amount", calcCommission(0, 0, 91));
        EXPECT_EQ("Invalid items' amount", calcCommission(0, 1, 0));
        EXPECT_EQ("Invalid items' amount", calcCommission(0, 1, 1));
        EXPECT_EQ("Invalid items' amount", calcCommission(0, 1, 2));
        EXPECT_EQ("Invalid items' amount", calcCommission(0, 1, 45));
        EXPECT_EQ("Invalid items' amount", calcCommission(0, 1, 89));
        EXPECT_EQ("Invalid items' amount", calcCommission(0, 1, 90));
        EXPECT_EQ("Invalid items' amount", calcCommission(0, 1, 91));
        EXPECT_EQ("Invalid items' amount", calcCommission(0, 2, 0));
        EXPECT_EQ("Invalid items' amount", calcCommission(0, 2, 1));
        EXPECT_EQ("Invalid items' amount", calcCommission(0, 2, 2));
        EXPECT_EQ("Invalid items' amount", calcCommission(0, 2, 45));
        EXPECT_EQ("Invalid items' amount", calcCommission(0, 2, 89));
        EXPECT_EQ("Invalid items' amount", calcCommission(0, 2, 90));
        EXPECT_EQ("Invalid items' amount", calcCommission(0, 2, 91));
        EXPECT_EQ("Invalid items' amount", calcCommission(0, 40, 0));
        EXPECT_EQ("Invalid items' amount", calcCommission(0, 40, 1));
        EXPECT_EQ("Invalid items' amount", calcCommission(0, 40, 2));
        EXPECT_EQ("Invalid items' amount", calcCommission(0, 40, 45));
        EXPECT_EQ("Invalid items' amount", calcCommission(0, 40, 89));
        EXPECT_EQ("Invalid items' amount", calcCommission(0, 40, 90));
        EXPECT_EQ("Invalid items' amount", calcCommission(0, 40, 91));
        EXPECT_EQ("Invalid items' amount", calcCommission(0, 79, 0));
        EXPECT_EQ("Invalid items' amount", calcCommission(0, 79, 1));
        EXPECT_EQ("Invalid items' amount", calcCommission(0, 79, 2));
        EXPECT_EQ("Invalid items' amount", calcCommission(0, 79, 45));
        EXPECT_EQ("Invalid items' amount", calcCommission(0, 79, 89));
        EXPECT_EQ("Invalid items' amount", calcCommission(0, 79, 90));
        EXPECT_EQ("Invalid items' amount", calcCommission(0, 79, 91));
        EXPECT_EQ("Invalid items' amount", calcCommission(0, 80, 0));
        EXPECT_EQ("Invalid items' amount", calcCommission(0, 80, 1));
        EXPECT_EQ("Invalid items' amount", calcCommission(0, 80, 2));
        EXPECT_EQ("Invalid items' amount", calcCommission(0, 80, 45));
        EXPECT_EQ("Invalid items' amount", calcCommission(0, 80, 89));
        EXPECT_EQ("Invalid items' amount", calcCommission(0, 80, 90));
        EXPECT_EQ("Invalid items' amount", calcCommission(0, 80, 91));
        EXPECT_EQ("Invalid items' amount", calcCommission(0, 81, 0));
        EXPECT_EQ("Invalid items' amount", calcCommission(0, 81, 1));
        EXPECT_EQ("Invalid items' amount", calcCommission(0, 81, 2));
        EXPECT_EQ("Invalid items' amount", calcCommission(0, 81, 45));
        EXPECT_EQ("Invalid items' amount", calcCommission(0, 81, 89));
        EXPECT_EQ("Invalid items' amount", calcCommission(0, 81, 90));
        EXPECT_EQ("Invalid items' amount", calcCommission(0, 81, 91));
        EXPECT_EQ("Invalid items' amount", calcCommission(1, 0, 0));
        EXPECT_EQ("Invalid items' amount", calcCommission(1, 0, 1));
        EXPECT_EQ("Invalid items' amount", calcCommission(1, 0, 2));
        EXPECT_EQ("Invalid items' amount", calcCommission(1, 0, 45));
        EXPECT_EQ("Invalid items' amount", calcCommission(1, 0, 89));
        EXPECT_EQ("Invalid items' amount", calcCommission(1, 0, 90));
        EXPECT_EQ("Invalid items' amount", calcCommission(1, 0, 91));
        EXPECT_EQ("Invalid items' amount", calcCommission(1, 1, 0));
        EXPECT_EQ("10", calcCommission(1, 1, 1));
        EXPECT_EQ("12.5", calcCommission(1, 1, 2));
        EXPECT_EQ("130", calcCommission(1, 1, 45));
        EXPECT_EQ("320", calcCommission(1, 1, 89));
        EXPECT_EQ("325", calcCommission(1, 1, 90));
        EXPECT_EQ("Invalid items' amount", calcCommission(1, 1, 91));
        EXPECT_EQ("Invalid items' amount", calcCommission(1, 2, 0));
        EXPECT_EQ("13", calcCommission(1, 2, 1));
        EXPECT_EQ("15.5", calcCommission(1, 2, 2));
        EXPECT_EQ("134.5", calcCommission(1, 2, 45));
        EXPECT_EQ("326", calcCommission(1, 2, 89));
        EXPECT_EQ("331", calcCommission(1, 2, 90));
        EXPECT_EQ("Invalid items' amount", calcCommission(1, 2, 91));
        EXPECT_EQ("Invalid items' amount", calcCommission(1, 40, 0));
        EXPECT_EQ("140.5", calcCommission(1, 40, 1));
        EXPECT_EQ("144.25", calcCommission(1, 40, 2));
        EXPECT_EQ("334", calcCommission(1, 40, 45));
        EXPECT_EQ("554", calcCommission(1, 40, 89));
        EXPECT_EQ("559", calcCommission(1, 40, 90));
        EXPECT_EQ("Invalid items' amount", calcCommission(1, 40, 91));
        EXPECT_EQ("Invalid items' amount", calcCommission(1, 79, 0));
        EXPECT_EQ("348", calcCommission(1, 79, 1));
        EXPECT_EQ("353", calcCommission(1, 79, 2));
        EXPECT_EQ("568", calcCommission(1, 79, 45));
        EXPECT_EQ("788", calcCommission(1, 79, 89));
        EXPECT_EQ("793", calcCommission(1, 79, 90));
        EXPECT_EQ("Invalid items' amount", calcCommission(1, 79, 91));
        EXPECT_EQ("Invalid items' amount", calcCommission(1, 80, 0));
        EXPECT_EQ("354", calcCommission(1, 80, 1));
        EXPECT_EQ("359", calcCommission(1, 80, 2));
        EXPECT_EQ("574", calcCommission(1, 80, 45));
        EXPECT_EQ("794", calcCommission(1, 80, 89));
        EXPECT_EQ("799", calcCommission(1, 80, 90));
        EXPECT_EQ("Invalid items' amount", calcCommission(1, 80, 91));
        EXPECT_EQ("Invalid items' amount", calcCommission(1, 81, 0));
        EXPECT_EQ("Invalid items' amount", calcCommission(1, 81, 1));
        EXPECT_EQ("Invalid items' amount", calcCommission(1, 81, 2));
        EXPECT_EQ("Invalid items' amount", calcCommission(1, 81, 45));
        EXPECT_EQ("Invalid items' amount", calcCommission(1, 81, 89));
        EXPECT_EQ("Invalid items' amount", calcCommission(1, 81, 90));
        EXPECT_EQ("Invalid items' amount", calcCommission(1, 81, 91));
        EXPECT_EQ("Invalid items' amount", calcCommission(2, 0, 0));
        EXPECT_EQ("Invalid items' amount", calcCommission(2, 0, 1));
        EXPECT_EQ("Invalid items' amount", calcCommission(2, 0, 2));
        EXPECT_EQ("Invalid items' amount", calcCommission(2, 0, 45));
        EXPECT_EQ("Invalid items' amount", calcCommission(2, 0, 89));
        EXPECT_EQ("Invalid items' amount", calcCommission(2, 0, 90));
        EXPECT_EQ("Invalid items' amount", calcCommission(2, 0, 91));
        EXPECT_EQ("Invalid items' amount", calcCommission(2, 1, 0));
        EXPECT_EQ("14.5", calcCommission(2, 1, 1));
        EXPECT_EQ("17", calcCommission(2, 1, 2));
        EXPECT_EQ("136.75", calcCommission(2, 1, 45));
        EXPECT_EQ("329", calcCommission(2, 1, 89));
        EXPECT_EQ("334", calcCommission(2, 1, 90));
        EXPECT_EQ("Invalid items' amount", calcCommission(2, 1, 91));
        EXPECT_EQ("Invalid items' amount", calcCommission(2, 2, 0));
        EXPECT_EQ("17.5", calcCommission(2, 2, 1));
        EXPECT_EQ("20", calcCommission(2, 2, 2));
        EXPECT_EQ("141.25", calcCommission(2, 2, 45));
        EXPECT_EQ("335", calcCommission(2, 2, 89));
        EXPECT_EQ("340", calcCommission(2, 2, 90));
        EXPECT_EQ("Invalid items' amount", calcCommission(2, 2, 91));
        EXPECT_EQ("Invalid items' amount", calcCommission(2, 40, 0));
        EXPECT_EQ("147.25", calcCommission(2, 40, 1));
        EXPECT_EQ("151", calcCommission(2, 40, 2));
        EXPECT_EQ("343", calcCommission(2, 40, 45));
        EXPECT_EQ("563", calcCommission(2, 40, 89));
        EXPECT_EQ("568", calcCommission(2, 40, 90));
        EXPECT_EQ("Invalid items' amount", calcCommission(2, 40, 91));
        EXPECT_EQ("Invalid items' amount", calcCommission(2, 79, 0));
        EXPECT_EQ("357", calcCommission(2, 79, 1));
        EXPECT_EQ("362", calcCommission(2, 79, 2));
        EXPECT_EQ("577", calcCommission(2, 79, 45));
        EXPECT_EQ("797", calcCommission(2, 79, 89));
        EXPECT_EQ("802", calcCommission(2, 79, 90));
        EXPECT_EQ("Invalid items' amount", calcCommission(2, 79, 91));
        EXPECT_EQ("Invalid items' amount", calcCommission(2, 80, 0));
        EXPECT_EQ("363", calcCommission(2, 80, 1));
        EXPECT_EQ("368", calcCommission(2, 80, 2));
        EXPECT_EQ("583", calcCommission(2, 80, 45));
        EXPECT_EQ("803", calcCommission(2, 80, 89));
        EXPECT_EQ("808", calcCommission(2, 80, 90));
        EXPECT_EQ("Invalid items' amount", calcCommission(2, 80, 91));
        EXPECT_EQ("Invalid items' amount", calcCommission(2, 81, 0));
        EXPECT_EQ("Invalid items' amount", calcCommission(2, 81, 1));
        EXPECT_EQ("Invalid items' amount", calcCommission(2, 81, 2));
        EXPECT_EQ("Invalid items' amount", calcCommission(2, 81, 45));
        EXPECT_EQ("Invalid items' amount", calcCommission(2, 81, 89));
        EXPECT_EQ("Invalid items' amount", calcCommission(2, 81, 90));
        EXPECT_EQ("Invalid items' amount", calcCommission(2, 81, 91));
        EXPECT_EQ("Invalid items' amount", calcCommission(35, 0, 0));
        EXPECT_EQ("Invalid items' amount", calcCommission(35, 0, 1));
        EXPECT_EQ("Invalid items' amount", calcCommission(35, 0, 2));
        EXPECT_EQ("Invalid items' amount", calcCommission(35, 0, 45));
        EXPECT_EQ("Invalid items' amount", calcCommission(35, 0, 89));
        EXPECT_EQ("Invalid items' amount", calcCommission(35, 0, 90));
        EXPECT_EQ("Invalid items' amount", calcCommission(35, 0, 91));
        EXPECT_EQ("Invalid items' amount", calcCommission(35, 1, 0));
        EXPECT_EQ("194.5", calcCommission(35, 1, 1));
        EXPECT_EQ("198.25", calcCommission(35, 1, 2));
        EXPECT_EQ("406", calcCommission(35, 1, 45));
        EXPECT_EQ("626", calcCommission(35, 1, 89));
        EXPECT_EQ("631", calcCommission(35, 1, 90));
        EXPECT_EQ("Invalid items' amount", calcCommission(35, 1, 91));
        EXPECT_EQ("Invalid items' amount", calcCommission(35, 2, 0));
        EXPECT_EQ("199", calcCommission(35, 2, 1));
        EXPECT_EQ("202.75", calcCommission(35, 2, 2));
        EXPECT_EQ("412", calcCommission(35, 2, 45));
        EXPECT_EQ("632", calcCommission(35, 2, 89));
        EXPECT_EQ("637", calcCommission(35, 2, 90));
        EXPECT_EQ("Invalid items' amount", calcCommission(35, 2, 91));
        EXPECT_EQ("Invalid items' amount", calcCommission(35, 40, 0));
        EXPECT_EQ("420", calcCommission(35, 40, 1));
        EXPECT_EQ("425", calcCommission(35, 40, 2));
        EXPECT_EQ("640", calcCommission(35, 40, 45));
        EXPECT_EQ("860", calcCommission(35, 40, 89));
        EXPECT_EQ("865", calcCommission(35, 40, 90));
        EXPECT_EQ("Invalid items' amount", calcCommission(35, 40, 91));
        EXPECT_EQ("Invalid items' amount", calcCommission(35, 79, 0));
        EXPECT_EQ("654", calcCommission(35, 79, 1));
        EXPECT_EQ("659", calcCommission(35, 79, 2));
        EXPECT_EQ("874", calcCommission(35, 79, 45));
        EXPECT_EQ("1094", calcCommission(35, 79, 89));
        EXPECT_EQ("1099", calcCommission(35, 79, 90));
        EXPECT_EQ("Invalid items' amount", calcCommission(35, 79, 91));
        EXPECT_EQ("Invalid items' amount", calcCommission(35, 80, 0));
        EXPECT_EQ("660", calcCommission(35, 80, 1));
        EXPECT_EQ("665", calcCommission(35, 80, 2));
        EXPECT_EQ("880", calcCommission(35, 80, 45));
        EXPECT_EQ("1100", calcCommission(35, 80, 89));
        EXPECT_EQ("1105", calcCommission(35, 80, 90));
        EXPECT_EQ("Invalid items' amount", calcCommission(35, 80, 91));
        EXPECT_EQ("Invalid items' amount", calcCommission(35, 81, 0));
        EXPECT_EQ("Invalid items' amount", calcCommission(35, 81, 1));
        EXPECT_EQ("Invalid items' amount", calcCommission(35, 81, 2));
        EXPECT_EQ("Invalid items' amount", calcCommission(35, 81, 45));
        EXPECT_EQ("Invalid items' amount", calcCommission(35, 81, 89));
        EXPECT_EQ("Invalid items' amount", calcCommission(35, 81, 90));
        EXPECT_EQ("Invalid items' amount", calcCommission(35, 81, 91));
        EXPECT_EQ("Invalid items' amount", calcCommission(69, 0, 0));
        EXPECT_EQ("Invalid items' amount", calcCommission(69, 0, 1));
        EXPECT_EQ("Invalid items' amount", calcCommission(69, 0, 2));
        EXPECT_EQ("Invalid items' amount", calcCommission(69, 0, 45));
        EXPECT_EQ("Invalid items' amount", calcCommission(69, 0, 89));
        EXPECT_EQ("Invalid items' amount", calcCommission(69, 0, 90));
        EXPECT_EQ("Invalid items' amount", calcCommission(69, 0, 91));
        EXPECT_EQ("Invalid items' amount", calcCommission(69, 1, 0));
        EXPECT_EQ("492", calcCommission(69, 1, 1));
        EXPECT_EQ("497", calcCommission(69, 1, 2));
        EXPECT_EQ("712", calcCommission(69, 1, 45));
        EXPECT_EQ("932", calcCommission(69, 1, 89));
        EXPECT_EQ("937", calcCommission(69, 1, 90));
        EXPECT_EQ("Invalid items' amount", calcCommission(69, 1, 91));
        EXPECT_EQ("Invalid items' amount", calcCommission(69, 2, 0));
        EXPECT_EQ("498", calcCommission(69, 2, 1));
        EXPECT_EQ("503", calcCommission(69, 2, 2));
        EXPECT_EQ("718", calcCommission(69, 2, 45));
        EXPECT_EQ("938", calcCommission(69, 2, 89));
        EXPECT_EQ("943", calcCommission(69, 2, 90));
        EXPECT_EQ("Invalid items' amount", calcCommission(69, 2, 91));
        EXPECT_EQ("Invalid items' amount", calcCommission(69, 40, 0));
        EXPECT_EQ("726", calcCommission(69, 40, 1));
        EXPECT_EQ("731", calcCommission(69, 40, 2));
        EXPECT_EQ("946", calcCommission(69, 40, 45));
        EXPECT_EQ("1166", calcCommission(69, 40, 89));
        EXPECT_EQ("1171", calcCommission(69, 40, 90));
        EXPECT_EQ("Invalid items' amount", calcCommission(69, 40, 91));
        EXPECT_EQ("Invalid items' amount", calcCommission(69, 79, 0));
        EXPECT_EQ("960", calcCommission(69, 79, 1));
        EXPECT_EQ("965", calcCommission(69, 79, 2));
        EXPECT_EQ("1180", calcCommission(69, 79, 45));
        EXPECT_EQ("1400", calcCommission(69, 79, 89));
        EXPECT_EQ("1405", calcCommission(69, 79, 90));
        EXPECT_EQ("Invalid items' amount", calcCommission(69, 79, 91));
        EXPECT_EQ("Invalid items' amount", calcCommission(69, 80, 0));
        EXPECT_EQ("966", calcCommission(69, 80, 1));
        EXPECT_EQ("971", calcCommission(69, 80, 2));
        EXPECT_EQ("1186", calcCommission(69, 80, 45));
        EXPECT_EQ("1406", calcCommission(69, 80, 89));
        EXPECT_EQ("1411", calcCommission(69, 80, 90));
        EXPECT_EQ("Invalid items' amount", calcCommission(69, 80, 91));
        EXPECT_EQ("Invalid items' amount", calcCommission(69, 81, 0));
        EXPECT_EQ("Invalid items' amount", calcCommission(69, 81, 1));
        EXPECT_EQ("Invalid items' amount", calcCommission(69, 81, 2));
        EXPECT_EQ("Invalid items' amount", calcCommission(69, 81, 45));
        EXPECT_EQ("Invalid items' amount", calcCommission(69, 81, 89));
        EXPECT_EQ("Invalid items' amount", calcCommission(69, 81, 90));
        EXPECT_EQ("Invalid items' amount", calcCommission(69, 81, 91));
        EXPECT_EQ("Invalid items' amount", calcCommission(70, 0, 0));
        EXPECT_EQ("Invalid items' amount", calcCommission(70, 0, 1));
        EXPECT_EQ("Invalid items' amount", calcCommission(70, 0, 2));
        EXPECT_EQ("Invalid items' amount", calcCommission(70, 0, 45));
        EXPECT_EQ("Invalid items' amount", calcCommission(70, 0, 89));
        EXPECT_EQ("Invalid items' amount", calcCommission(70, 0, 90));
        EXPECT_EQ("Invalid items' amount", calcCommission(70, 0, 91));
        EXPECT_EQ("Invalid items' amount", calcCommission(70, 1, 0));
        EXPECT_EQ("501", calcCommission(70, 1, 1));
        EXPECT_EQ("506", calcCommission(70, 1, 2));
        EXPECT_EQ("721", calcCommission(70, 1, 45));
        EXPECT_EQ("941", calcCommission(70, 1, 89));
        EXPECT_EQ("946", calcCommission(70, 1, 90));
        EXPECT_EQ("Invalid items' amount", calcCommission(70, 1, 91));
        EXPECT_EQ("Invalid items' amount", calcCommission(70, 2, 0));
        EXPECT_EQ("507", calcCommission(70, 2, 1));
        EXPECT_EQ("512", calcCommission(70, 2, 2));
        EXPECT_EQ("727", calcCommission(70, 2, 45));
        EXPECT_EQ("947", calcCommission(70, 2, 89));
        EXPECT_EQ("952", calcCommission(70, 2, 90));
        EXPECT_EQ("Invalid items' amount", calcCommission(70, 2, 91));
        EXPECT_EQ("Invalid items' amount", calcCommission(70, 40, 0));
        EXPECT_EQ("735", calcCommission(70, 40, 1));
        EXPECT_EQ("740", calcCommission(70, 40, 2));
        EXPECT_EQ("955", calcCommission(70, 40, 45));
        EXPECT_EQ("1175", calcCommission(70, 40, 89));
        EXPECT_EQ("1180", calcCommission(70, 40, 90));
        EXPECT_EQ("Invalid items' amount", calcCommission(70, 40, 91));
        EXPECT_EQ("Invalid items' amount", calcCommission(70, 79, 0));
        EXPECT_EQ("969", calcCommission(70, 79, 1));
        EXPECT_EQ("974", calcCommission(70, 79, 2));
        EXPECT_EQ("1189", calcCommission(70, 79, 45));
        EXPECT_EQ("1409", calcCommission(70, 79, 89));
        EXPECT_EQ("1414", calcCommission(70, 79, 90));
        EXPECT_EQ("Invalid items' amount", calcCommission(70, 79, 91));
        EXPECT_EQ("Invalid items' amount", calcCommission(70, 80, 0));
        EXPECT_EQ("975", calcCommission(70, 80, 1));
        EXPECT_EQ("980", calcCommission(70, 80, 2));
        EXPECT_EQ("1195", calcCommission(70, 80, 45));
        EXPECT_EQ("1415", calcCommission(70, 80, 89));
        EXPECT_EQ("1420", calcCommission(70, 80, 90));
        EXPECT_EQ("Invalid items' amount", calcCommission(70, 80, 91));
        EXPECT_EQ("Invalid items' amount", calcCommission(70, 81, 0));
        EXPECT_EQ("Invalid items' amount", calcCommission(70, 81, 1));
        EXPECT_EQ("Invalid items' amount", calcCommission(70, 81, 2));
        EXPECT_EQ("Invalid items' amount", calcCommission(70, 81, 45));
        EXPECT_EQ("Invalid items' amount", calcCommission(70, 81, 89));
        EXPECT_EQ("Invalid items' amount", calcCommission(70, 81, 90));
        EXPECT_EQ("Invalid items' amount", calcCommission(70, 81, 91));
        EXPECT_EQ("Invalid items' amount", calcCommission(71, 0, 0));
        EXPECT_EQ("Invalid items' amount", calcCommission(71, 0, 1));
        EXPECT_EQ("Invalid items' amount", calcCommission(71, 0, 2));
        EXPECT_EQ("Invalid items' amount", calcCommission(71, 0, 45));
        EXPECT_EQ("Invalid items' amount", calcCommission(71, 0, 89));
        EXPECT_EQ("Invalid items' amount", calcCommission(71, 0, 90));
        EXPECT_EQ("Invalid items' amount", calcCommission(71, 0, 91));
        EXPECT_EQ("Invalid items' amount", calcCommission(71, 1, 0));
        EXPECT_EQ("Invalid items' amount", calcCommission(71, 1, 1));
        EXPECT_EQ("Invalid items' amount", calcCommission(71, 1, 2));
        EXPECT_EQ("Invalid items' amount", calcCommission(71, 1, 45));
        EXPECT_EQ("Invalid items' amount", calcCommission(71, 1, 89));
        EXPECT_EQ("Invalid items' amount", calcCommission(71, 1, 90));
        EXPECT_EQ("Invalid items' amount", calcCommission(71, 1, 91));
        EXPECT_EQ("Invalid items' amount", calcCommission(71, 2, 0));
        EXPECT_EQ("Invalid items' amount", calcCommission(71, 2, 1));
        EXPECT_EQ("Invalid items' amount", calcCommission(71, 2, 2));
        EXPECT_EQ("Invalid items' amount", calcCommission(71, 2, 45));
        EXPECT_EQ("Invalid items' amount", calcCommission(71, 2, 89));
        EXPECT_EQ("Invalid items' amount", calcCommission(71, 2, 90));
        EXPECT_EQ("Invalid items' amount", calcCommission(71, 2, 91));
        EXPECT_EQ("Invalid items' amount", calcCommission(71, 40, 0));
        EXPECT_EQ("Invalid items' amount", calcCommission(71, 40, 1));
        EXPECT_EQ("Invalid items' amount", calcCommission(71, 40, 2));
        EXPECT_EQ("Invalid items' amount", calcCommission(71, 40, 45));
        EXPECT_EQ("Invalid items' amount", calcCommission(71, 40, 89));
        EXPECT_EQ("Invalid items' amount", calcCommission(71, 40, 90));
        EXPECT_EQ("Invalid items' amount", calcCommission(71, 40, 91));
        EXPECT_EQ("Invalid items' amount", calcCommission(71, 79, 0));
        EXPECT_EQ("Invalid items' amount", calcCommission(71, 79, 1));
        EXPECT_EQ("Invalid items' amount", calcCommission(71, 79, 2));
        EXPECT_EQ("Invalid items' amount", calcCommission(71, 79, 45));
        EXPECT_EQ("Invalid items' amount", calcCommission(71, 79, 89));
        EXPECT_EQ("Invalid items' amount", calcCommission(71, 79, 90));
        EXPECT_EQ("Invalid items' amount", calcCommission(71, 79, 91));
        EXPECT_EQ("Invalid items' amount", calcCommission(71, 80, 0));
        EXPECT_EQ("Invalid items' amount", calcCommission(71, 80, 1));
        EXPECT_EQ("Invalid items' amount", calcCommission(71, 80, 2));
        EXPECT_EQ("Invalid items' amount", calcCommission(71, 80, 45));
        EXPECT_EQ("Invalid items' amount", calcCommission(71, 80, 89));
        EXPECT_EQ("Invalid items' amount", calcCommission(71, 80, 90));
        EXPECT_EQ("Invalid items' amount", calcCommission(71, 80, 91));
        EXPECT_EQ("Invalid items' amount", calcCommission(71, 81, 0));
        EXPECT_EQ("Invalid items' amount", calcCommission(71, 81, 1));
        EXPECT_EQ("Invalid items' amount", calcCommission(71, 81, 2));
        EXPECT_EQ("Invalid items' amount", calcCommission(71, 81, 45));
        EXPECT_EQ("Invalid items' amount", calcCommission(71, 81, 89));
        EXPECT_EQ("Invalid items' amount", calcCommission(71, 81, 90));
        EXPECT_EQ("Invalid items' amount", calcCommission(71, 81, 91));
    }

    TEST(EquivenceClass, StrongNormalRobust){
        EXPECT_EQ("100", calcCommission(10, 10, 10));
        EXPECT_EQ("Program terminates", calcCommission(-1, 40, 45));
        EXPECT_EQ("Invalid items' amount", calcCommission(-2, 40, 45));
        EXPECT_EQ("Invalid items' amount", calcCommission(35, -1, 45));
        EXPECT_EQ("Invalid items' amount", calcCommission(35, 40, -1));
        EXPECT_EQ("Invalid items' amount", calcCommission(-2, -1, 45));
        EXPECT_EQ("Invalid items' amount", calcCommission(35, -1, -1));
        EXPECT_EQ("Invalid items' amount", calcCommission(-2, 40, -1));
        EXPECT_EQ("Invalid items' amount", calcCommission(-2, -1, -1));
        EXPECT_EQ("Invalid items' amount", calcCommission(71, 40, 45));
        EXPECT_EQ("Invalid items' amount", calcCommission(35, 81, 45));
        EXPECT_EQ("Invalid items' amount", calcCommission(35, 40, 91));
        EXPECT_EQ("Invalid items' amount", calcCommission(71, 81, 45));
        EXPECT_EQ("Invalid items' amount", calcCommission(35, 81, 91));
        EXPECT_EQ("Invalid items' amount", calcCommission(71, 40, 91));
        EXPECT_EQ("Invalid items' amount", calcCommission(71, 81, 91));
    }

    TEST(EdgeValue, TestCase){
        EXPECT_EQ("Program terminates", calcCommission(-1, 40, 45));
        EXPECT_EQ("Invalid items' amount", calcCommission(-2, 40, 45));
    }
}